//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oefXMLKlanten
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klanten
    {
        public string Klantnummer { get; set; }
        public string Bedrijf { get; set; }
        public string Adres { get; set; }
        public string Plaats { get; set; }
        public string Postcode { get; set; }
        public string Land { get; set; }
        public string Telefoonnummer { get; set; }
    }
}
